//cake pieces
polyCylinder -r 2 -h 1 -sx 20 -sy 1 -sz 1 -ax 0 1 0 -rcp 0 -cuv 3 -ch 1;
move -r 0 .5 0 ;
rename "Tier_1";

polyCylinder -r 1.5 -h 1 -sx 20 -sy 1 -sz 1 -ax 0 1 0 -rcp 0 -cuv 3 -ch 1;
move -r 0 1 0 ;
rename "Tier_2";

polyCylinder -r 1 -h 1 -sx 20 -sy 1 -sz 1 -ax 0 1 0 -rcp 0 -cuv 3 -ch 1;
move -r 0 1.5 0 ;
rename "Tier_3";

$tiers[0] = "Tier_1";
$tiers[1] = "Tier_2";
$tiers[2] = "Tier_3";
print $tiers;